templates:
  scm-init: git
  params:
    # author-name: 
    # author-email: 
    # category: Experiment
    # copyright: 
    # github-username: 

default-template: /home/ユーザー名/.stack/templates/my.hsfiles

